export type SerializedArchivedProject = {
  id: string;
  title: string;
  description: string | null;
  features: string | null;
  tools: string | null;
  githubUrl: string | null;
  demoUrl: string | null;
  videoUrl: string | null;
  imageUrl: string | null;
  linkUrl: string | null;
  promptResult: string | null;
  promptFeedback: string | null;
  promptScore: number | null;
  catFeedback: string | null;
  catScore: number | null;
  isFinals: boolean;
  finalsRank: number | null;
  adminMemo: string | null;
  voteCount: number;
  likeCount: number;
  teamName: string | null;
  motivation: string | null;
  recruitmentNote: string | null;
  experienceLevel: string | null;
  members: unknown;
  originalProjectId: string | null;
  createdAt: string;
};
